struct job_metadata {
	int type; /* Store type of job to be performed*/
	/*
	 * Job_ID will be generated by producer
	 * and will be used to remove a job and will be listed to user when user
	 * says to list all jobs in the list
	 */	
	int job_id;
	char *input_file;
	char *output_file;
	char *key;
	char *algorithm;

	/*
	 * int priority;
	 */
	int no_of_files; /* this variable will store the number of files*/
}((__attribute_packed__));

//struct job_queue {
//	struct list_head job_q;	/*Queue to hold jobs */
//	struct job_metadata job_d; /* Jon specific data */
//};

